apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tlsecho-bs
  annotations:
    github.com/project-slug: ajcross/tlsecho-bs
spec:
  type: other
  lifecycle: unknown
  owner: guests

